<?php
$helper = Mage::helper("corevalue_facebookpixel");
if (!$helper->isPixelEnabled() || !$helper->isConversionEnabled()) {
    return;
}
$pixelId = $helper->getPixelId();
/**
 * @var $_product Mage_Catalog_Model_Product
 */
$_product = Mage::getModel('core/session')->getProductToShoppingCart();
?>
<?php if ($_product && $_product->getId()): ?>
    <script>
        fbq('track', 'AddToCart', {
            content_name: '<?php echo $_product->getName() ?>',
            content_type: 'product',
            content_ids: '<?php echo $_product->getSku()?>',
            value: '<?php echo number_format((float)$_product->getPrice(), 2, '.', '');?>',
            currency: '<?php echo Mage::app()->getStore()->getCurrentCurrencyCode();?>'
        });
    </script>
    <?php Mage::getModel('core/session')->unsProductToShoppingCart(); ?>
<?php endif; ?>